[build-system]
requires = ["setuptools>=0.61", "pandas", "numpy", "gensim", "requests", "tokenizers==0.15.2", "fire", "h5py", "gloves @ git+https://github.com/eldrin/gloves@master", "sentence-transformers==2.2.2"]
build-backend = "setuptools.build_meta"
