[build-system]
requires = ["setuptools>=0.61", "pandas", "numpy", "gensim", "requests", "tokenizers", "fire", "h5py", "gloves @ git+https://github.com/eldrin/gloves@master"]
build-backend = "setuptools.build_meta"
