name: Python package

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
